# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  twitter_oauth_class: Abraham\TwitterOAuth\TwitterOAuth
  twitter_consumer_key: 55rheipAflYpFF2j4Vm9gSPw4
  twitter_consumer_secret: 75L0rGl8xMjwZMb3oZnG0BGnvS3Wik5opwcrDv49rsVAyi68mZ

services:
  twitter_oauth:
    class:     Abraham\TwitterOAuth\TwitterOAuth
    arguments: ['%twitter_consumer_key%', '%twitter_consumer_secret%']
  app.tweet_fetcher:
    class:     AppBundle\Service\TwitterCommunication\TweetFetcher
    arguments: ['@twitter_oauth', '@session', '%twitter_callback_url%']
  app.home_page_controller:
    class:     AppBundle\Controller\HomePageController
    arguments: ['@app.tweet_fetcher', '@templating', '@router', '@session']
  app.twitter_authorisation:
    class:     AppBundle\Controller\TwitterAuthorisation\TwitterAuthorisationController
    arguments: ['@app.tweet_fetcher', '@session', '@router']
